### ISSUE TITLE
[Group Request] Create a new chapter in Lehi, Utah

### ISSUE THREAD

**Issue by clintberry** [cncf/communitygroups#168]
### City or location name for your CNCG

Lehi, Utah

### What country do you want to start your community group in?

United States

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Clint Berry, clint@theforge.tech, https://github.com/clintberry, https://www.linkedin.com/in/clintonberry/,  https://cloud-native.slack.com/team/U07KNPAPBK3 , https://community.cncf.io/u/mmgg99

I started a not-for-profit, Forge Utah Foundation, to help grow technology education and talent in Utah. We run several free meetups for the community, including the Utah Kubernetes meetup which we have been running for almost 8 years. We have had over 90 meetups (Over 10/year) and average 34 RSVPs (pretty good for Utah). We have over 1200 members of the meetup. For all intents and purposes, we are the local CNCF chapter for Utah. We even had a Cloud Native Utah meetup before combining it with Utah Kubernetes since we typically wanted the same speakers: https://www.meetup.com/cloud-native-utah/

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

Paul McKay, https://www.linkedin.com/in/paul-mackay-bb5b51/
Paul McKay started the Utah Kubernetes meetup in January of 2017 when you worked at Ancestry.com. He has been the primary organizer for the last 7+ years and joined with Forge Utah as the org that helps manage and run the meetup. He is a seasoned engineering leader and lover of Kubernetes and all things CNCF.

### If you already run a meetup, please link it here

https://www.meetup.com/utah-kubernetes-meetup/

### What is your mission statement or objective for this new chapter?

We are a group of people passionate about cloud native technologies. We have been using Kubernetes in our companies for over 8 years and our mission is to help spread more knowledge about kubernetes and other cloud native technologies to our local communities to help their companies thrive. 

### Code of Conduct

- [x] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [x] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [x] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [x] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [x] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [x] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [x] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [x] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [x] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [x] I/We will do our best to host diverse speakers throughout the year

**Comment by AudMonte01** [comment]
Thank you, @clintberry for this submissions. It's great to see how active your current meetup is, and that you want this group to now be associated with CNCF as one of our chapters.

Since Lehi is not taken, but it is close to [our Salt Lake City chapter](https://community.cncf.io/salt-lake-city/), we highly encourage collaboration on speakers and promotions. Perhaps there can be some alternating co-hosting in our community.cncf.io platform we use, called Bevy. This would make it easy to uphold [the 90-day activity standard we have](https://github.com/cncf/communitygroups/blob/main/README.md#community-group-inactivity).

That said, I have moved forward with creating this chapter and added you as an organizer. Thank you for already having an account on community.cncf.io. Now we just need Paul to make one! Please tag his GitHub handle here to do this, as well as for him confirm he agrees to the above organizer terms.

Thanks again!

Audra Montenegro
CNCF Community Program Manager
community-groups@cncf.io
[Host or join a local community group](https://community.cncf.io/)
US Time zone: Pacific Standard Time

**Comment by AudMonte01** [comment]
Following up here, @clintberry - please tag Paul here with his GitHub handle, or let me know what email he uses for his community.cncf.io account. Thanks in advance!

**Comment by AudMonte01** [comment]
Since I have not received a response, I will close this ticket. Paul can re-open it if he would like to be added as a co-organizer.

@clintberry - please join one of my Friday office hours so I can help you get started: https://community.cncf.io/community-event-organizer-hub/.
