### ISSUE TITLE
[Group Request] Cloud Native Midtown

### ISSUE THREAD

**Issue by abebars** [cncf/communitygroups#50]
### City or location name for your CNCG

Cloud Native Engineering Midtown

### What country do you want to start your community group in?

United States

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Ahmed Bebars, The New York Times, Staff Software Engineer, [ahmed.bebars@cloudnativecommunity.io](mailto:ahmed.bebars@cloudnativecommunity.io), abebars

### Tell us about your co-organizer. List their name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if they need to be invited), and a required profile link on community.cncf.io

David Grizzanti, The New York Times, Principal Engineer, [david.grizzanti@nytimes.com](mailto:david.grizzanti@nytimes.com)

### What is your mission statement or objective for this new chapter?

Our mission is to empower and unite developers, operators, and technology enthusiasts through the exploration and understanding of promising new technologies within the Cloud Native Computing Foundation (CNCF) ecosystem. We are dedicated to fostering collaboration and bridging gaps between theory and practice. Our aim is to create a vibrant community where members can share insights, experiences, and best practices on how these technologies are being leveraged to drive innovation and solve real-world problems. By promoting an environment of learning and sharing, Cloud Native NYC strives to be at the forefront of technological advancement and a beacon for those navigating the evolving landscape of cloud native solutions.

### Code of Conduct

- [X] I/We agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizers reside

- [X] I/We confirm I/we am/are local to or live near the city of the above-proposed chapter.

### Organizers companies/affiliations

- [X] I/We agree if there is more than one organizer now or onboarded in the future, the majority come from different companies

### Inclusive

- [X] I/We agree. To assure this, I/we have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)

### Vendor Neutral

- [X] I/We have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and agree that the main content of our meetups will remain vendor-nuetral

### Agree to use CNCG branding

- [X] I/We agree to use the CNCG logo in my/our chapter and social branding

### Registration through CNCF platforms

- [X] I/We agree to host free registration in the main CNCF platform

### Remain an active chapter

- [X] I/We agree to have a meetup at least once every 90 days, or else communicate reasoning for upcoming inactivity.

### Collaboration with other chapters

- [X] I/We acknowledge the CNCF right to approve additional chapters in my area based on this criteria

### Aim to have a diverse representation of speakers in your meetups

- [X] I/We will do our best to host diverse speakers throughout the year

**Comment by k8tgreenley** [comment]
@abebars can you please provide the cadence of your meetup, i.e. will it be monthly, quarterly, etc.? What day of the week will it be held? Typically, where will it be hosted (same location or different locations)?

**Comment by k8tgreenley** [comment]
Is there a specific audience you are trying to reach?

**Comment by abebars** [comment]
> @abebars can you please provide the cadence of your meetup, i.e. will it be monthly, quarterly, etc.? What day of the week will it be held? Typically, where will it be hosted (same location or different locations)? 

We are aiming for monthly but that may change based on availability and speakers.

Location is NYTimes Building at first but we are open to other available locations

**Comment by abebars** [comment]
> Is there a specific audience you are trying to reach?

Target is mainly Engineering community between entry level and well experienced industry professionals.

**Comment by k8tgreenley** [comment]
@abebars What are the days of the week you are planning to host this?

**Comment by k8tgreenley** [comment]
Can you please clarify how this new group will differ from the https://community.cncf.io/new-york-kubernetes-meetup/?

**Comment by abebars** [comment]
> @abebars What are the days of the week you are planning to host this?

There is no specific day to host the events yet, but we are going to target consistent days if possible.

**Comment by abebars** [comment]
> Can you please clarify how this new group will differ from the https://community.cncf.io/new-york-kubernetes-meetup/?

@k8tgreenley One of the main goals for the group is to focus on a few areas related to platform engineering based on CNCF tooling and also find a consistent way to meet and plan to host events both in-person and virtually to expand the reach.

**Comment by abebars** [comment]
@k8tgreenley, can you also please help me understand the timeline for getting the group created? I am working with a few speakers on hosting the first event soon, and I just want to make sure we have enough lead time to plan and amplify the event.

**Comment by k8tgreenley** [comment]
Please explain why you cannot collaborate within the existing New York chapter? 

You have noted that you had ideas for the meetup that differed from the current one. What are the ideas or formats that will be different from the current chapter?

**Comment by abebars** [comment]
> Please explain why you cannot collaborate within the existing New York chapter? 
> 
> 
> 
> You have noted that you had ideas for the meetup that differed from the current one. What are the ideas or formats that will be different from the current chapter?

My earlier attempts to collaborate with the organizers didn't go as expected. There are different cadence , ideas and medium that I didn't align with current group on.
(I believe I expressed that earlier a few times) let me know if that's is going to be issue of having multiple community groups for a city like New York. I thought having more groups would expand the reach given that the audience are significantly larger to the current offering and operation we have.

**Comment by k8tgreenley** [comment]
@abebars, I need additional clarification and details about how your meetup group will differ and how the collaboration didn't go as expected.

Currently, this request seems to be a duplicate effort of the Kubernetes New York group with similar missions, similar audiences, and locations both in midtown.

**Comment by abebars** [comment]
> @abebars, I need additional clarification and details about how your meetup group will differ and how the collaboration didn't go as expected.
> 
> Currently, this request seems to be a duplicate effort of the Kubernetes New York group, which has similar missions, audiences, and locations in midtown.

@k8tgreenley The New Group is Targeting both in-person and Virtual Events. The main core topic will be Platform Engineering in the CNCF Landscape. 
As of now, the target plan is as follows:
- In-Person Monthly or Bi-Monthly Event on **Thursdays** at The New York Times (Or Other applicable venues).
- Virtual Panels to discuss Trends in Platform Engineering and CNCF Tooling (Date not set yet).

The dates and topics of the New Chapter will be discussed to avoid conflict with the current chapter.

More Context: I reached out to the current group a few times, and the latest conversation led to a conflict of interest mainly around the group's purpose and being territorial about what other people would be able to contribute to the community; at the current point, I prefer to help anyone in the community and all CNCF Groups, including K8s NYC, without being directly involved in organizing events with the K8s NYC.

Please let me know if there is any other information is requested.

**Comment by karenhchu** [comment]
We do not object to a second group and just ask that such proposals are transparent.

The name originally proposed had the potential to cause confusion. We are happy to see it has been updated to "Cloud Native Engineering Midtown" which better aligns to the more specific, local, geographies agreed upon for new groups or sub-groups. 

We wish Ahmed and the “Cloud Native Engineering Midtown” group good luck in expanding the options available to the NYC Cloud Native community.

This comment was drafted collaboratively by the NYCK8s organizers - @karenhchu, @arieljatib, @scottrigby, and @TonyMarfil.

**Comment by abebars** [comment]
> We do not object to a second group and just ask that such proposals are transparent.
> 
> The name originally proposed had the potential to cause confusion. We are happy to see it has been updated to "Cloud Native Engineering Midtown" which better aligns to the more specific, local, geographies agreed upon for new groups or sub-groups.
> 
> We wish Ahmed and the “Cloud Native Engineering Midtown” group good luck in expanding the options available to the NYC Cloud Native community.
> 
> This comment was drafted collaboratively by the NYCK8s organizers - @karenhchu, @arieljatib, @scottrigby, and @TonyMarfil.

Thanks @karenhchu. I appreciate the response and looking forward to having more groups in NY that strengthen the community and have a bigger impact. 

@k8tgreenley Can we now move forward with the group? Also, now that we have 2 groups in NY, I am assuming that we will have a parent chapter named Cloud Native New York to Include All Subgroups, correct?

**Comment by scottrigby** [comment]
@abebars as initially proposed, i agreed with @k8tgreenley that this seemed like a duplicate group. There was/is not a significant difference  in the proposed cadence, medium, or purpose. I clarified that to you in our last conversation (I'm happy to publicly address those point-by-point any time, but that seems unnecessary to do here since you've changed the group name to be more specific). As @karenhchu said, we have no problem with a neighborhood-specific group as you're proposing now, since that seems to be a clear reason for a separate group (instead of contributing to the existing group as the community is generally encouraged to do). your proposed new group name is better since it removes the strong potential for community confusion i saw in your original proposal. This potential for confusion (and the fragmentation that usually comes with it) was my main reason for wanting a transparent process.

However your last comment seems to be trying to widen the scope of your proposal again. You said:

> Also, now that we have 2 groups in NY, I am assuming that we will have a parent chapter named Cloud Native New York to Include All Subgroups, correct?

As you know (because we discussed this), the existing NYC group was already in the process of a name change in coordination with CNCF, to include "Cloud Native" in the group name. (we agreed to update the name to "Kubernetes + Cloud Native New York," following the same name change pattern that KubeCon made when changing to "KubeCon + CloudNativeCon").

But either way, what could your reasons be for asking CNCF to change the status of the existing NYC community group - which has been representing CNCF in all of New York City since 2015 - to also become a subgroup?

I thought you opened this issue to propose a new (now neighborhood-specific) chapter in a city with an existing Cloud Native group. Is that right? Or is this issue proposing more than that?

**Comment by arieljatib** [comment]
Ahmed, I appreciate your persistence in sharing your thoughts, but I must say that I’m a bit disappointed by the tone of your messages and accusations. As you know, we’ve been open to collaboration and feedback throughout this process.

While I understand your desire to avoid discussing the reasons behind your decision to start another group, it’s essential to acknowledge the history and context surrounding NYCK8s’ revival. Your assertion that we’re not operating in good faith is unwarranted and unfair.

> In the past 180 days, There were only two meetups in NYC (I am well aware that's within the CNCF Rule of at least one event every 90 Days). But I am more ambitious and looking to be able to make a significant impact by stretching out the goals and reach a bigger audience.

We've discussed with you how finding a venue has been a key challenge in restarting the group. At the first (and only) NYCK8s event you attended in January, we discussed how we might collaborate in the future, agreeing to focus on hosting an event at the NYT. We followed up on email, including mention of our next, and most recent event, in April for Earth Day. We never heard back from you.

>  I want to avoid getting into more conversations about why we are starting another group here since you allotted to it in your response.

There’s a phrase - “good fences make good neighbors”. Clearly defining scope and purpose is important, and a key aspect of this new process - it would seem. 

> According to the information I found on the internet and the meetup website, the current group only operated in Manhattan with a Couple of expectations to Brooklyn 

There are a variety of reasons for venue choices - access and availability are the two main ones. 

According to your LinkedIn profile, you've been in NYC since 2017. By our count, there were 38 events you could have attended in any of these neighborhoods. You have not and only joined the group on April 30th 2023, attending a total of one event. Participation in the group is essential to collaborating. You’ve not done that. 

> So Since More groups are being created in the Same state, It makes more sense that CNCF would create a Parent Chapter that includes all local chapters.

Your opinion is not informed by facts or historical context. There is currently a DC group and a NOVA group without a “parent group”. Historically, there have also been other groups in NYS, the Albany group comes to mind right away - I believe they were called the “Capital Region”.

Again, we wish you the best. Can we just move on and get back to focusing on organizing events?

**Comment by abebars** [comment]
@arieljatib Thanks for being diligent and finding the time to respond. 

> I’m a bit disappointed by the tone of your messages and accusations. As you know, we’ve been open to collaboration and feedback throughout this process.

I didn't make any and I am not planning to. 


> We've discussed with you how finding a venue has been a key challenge in restarting the group. At the first (and only) NYCK8s event you attended in January, we discussed how we might collaborate in the future, agreeing to focus on hosting an event at the NYT. We followed up on the email, including a mention of our next and most recent event, in April for Earth Day. We never heard back from you.

Achnolwqding that but I am not responding (Sorry, I am not getting into more details around that). We didn't speak after that but there was a lot of convo that I relied which is also my mistake that I didn't reach out to you directly.

> https://www.mapcustomizer.com/map/K8s%20NYC%20Meetup

I literally plotted a map with tens of locations, to be exact, about 54 since 2016. This shows that the group has had many events, and I am not getting into more details about that. There are historical events that I can see for the group, so I think I am well-informed but you can read my message.

> Your opinion is not informed by facts or historical context. There is currently a DC group and a NOVA group without a “parent group”. Historically, there have also been other groups in NYS, the Albany group comes to mind right away - I believe they were called the “Capital Region”.

That wasn't my original opinion btw, but I agree with it, and I don't see why everything when I mention it becomes a problem.

> Again, we wish you the best. Can we just move on and get back to focusing on organizing events?

I also wish you the same and I don't think I am holding anyone since I was the one who told to stop.

**Comment by scottrigby** [comment]
@k8tgreenley from our side we can close out this issue, as long as @abebars agrees to keep the issue scoped only to request a new official CNCF meetup in Midtown Manhattan. As long as that's the case, the [New York k8s Meetup group organizers have no problem with this](https://github.com/cncf/communitygroups/issues/50#issuecomment-2119503310). However, further comments since then made this unclear to me. 

@abebars can you confirm that you're not expanding the scope of this issue to include requests for additional things that could impact the New York Cloud native community, like:

1. requests for our long existing plan to rename of the original New York K8s group?
2. or requests about the name and function of a parent group on community.cncf.io that CNCF was already planning to roll out to multiple cities?

If this issue is also about those things too, then I think it requires further discussion. If not, then great! No further discussion necessary from our end.

**Comment by abebars** [comment]
> @k8tgreenley from our side we can close out this issue if @abebars confirms the issue is scoped only to request a new official CNCF meetup in Midtown Manhattan. If that's the case, the [New York k8s Meetup group organizers have no problem with this](https://github.com/cncf/communitygroups/issues/50#issuecomment-2119503310). However, further comments since then made this unclear to me.
> 
> @abebars can you confirm that you're not expanding the scope of this issue to include requests for additional things that could impact the New York Cloud native community, like:
> 
> 1. requests for our long existing plan to rename the original New York K8s group?
> 2. or requests about the name and function of a parent group on community.cncf.io that CNCF was already planning to roll out to multiple cities?
> 
> If this issue is also about those things too, then I think it requires further discussion. If not, then great! No further discussion necessary from our end.

This issue is focused on creating a new meetup chapter to increase the number of events in the community; the CNCF has discretion over anything else.

One more thing: **Cloud Native Engineering Midtown** seems to be confusing to people, and I would like to request just naming this Chapter **Cloud Native Midtown**; thank you all for chiming in and taking the time to get a resolution on that.

**Comment by scottrigby** [comment]
sgtm

**Comment by k8tgreenley** [comment]
Thank you, everyone, for the review, input, and discussion. I am going to close this ticket and move forward with the following next steps:

- Create New York parent chapter (admin rights will be with the CNCF team). This will serve as a central location for all New York based groups to be highlighted 
- Create Cloud Native Midtown chapter
- Create New York organizers private slack channel for transparency and communication. This can help prevent overlap of meetup dates or sharing speakers that might be a worth the other group hosting.
