### ISSUE TITLE
[Organizer Request] Add Yongkang as the lead organizer for Sydney

### ISSUE THREAD

**Issue by yongkanghe** [cncf/communitygroups#94]
### Name of chapter inquiring about

Sydney

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Yongkang He
yhe@yongkang.com.au
K8SUG
https://github.com/yongkanghe
https://linkedin.com/in/yongkanghe
yongkang
https://community.cncf.io/u/mvs8uf/#/about

### Tell us why you want to be added or removed from the chapter

Sydney community is not active for probably 1 year. I had very strong experience to help the community. I'd love to make it actively running. 

### Code of Conduct

- [X] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides

- [X] I confirm I am local to or live near the city of the above-proposed chapter (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [X] I come from xyz company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [X] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [X] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree the main content of our meetups will remain vendor-nuetral (do not mark if irrelevent to request)

### Remain an active chapter

- [X] I understand the activity level standards of all CNCF chapters (do not mark if irrelevent to request)

### Collaboration with other chapters

- [X] I acknowledge the CNCF right to approve additional chapters in my area based on this criteria (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your meetups

- [X] I will do my best to host diverse speakers throughout the year (do not mark if irrelevent to request)

**Comment by yongkanghe** [comment]
@AudMonte01 @k8tgreenley

**Comment by AudMonte01** [comment]
Please discuss becoming a co-organizer with the current KCD group, as they were intending to get the chapter up and running last year.

Ccing @bradmccoydev

**Comment by yongkanghe** [comment]
@bradmccoydev, please advise when you're available to have a chat?

**Comment by bradmccoydev** [comment]
Sorry for late reply let's catchup next week I will be free. Good timing actually as he want to do a meetup in July to help promote kubeday and kcd and have a belated k8s bday celebration, the more organisers the better!

**Comment by yongkanghe** [comment]
Great to hear, thanks Brad! Let's chat this week. Happy to help as much as I can. Here's my calendar. https://calendly.com/k8sug
[https://d3v0px0pttie1i.cloudfront.net/uploads/user/logo/33751186/opengraph_7b71b6b6.png?source=opengraph]<https://calendly.com/k8sug>
Yongkang He<https://calendly.com/k8sug>
Welcome to my scheduling page. Please follow the instructions to add an event to my calendar.
calendly.com

________________________________

**Comment by AudMonte01** [comment]
Thank you, both. Please follow up here with what comes of the meeting, @bradmccoydev

**Comment by yongkanghe** [comment]
Hi @bradmccoydev<https://github.com/bradmccoydev>, please let me know when you have a chance to chat. https://calendly.com/k8sug
________________________________

**Comment by yongkanghe** [comment]
@AudMonte01, I just spoke to @bradmccoydev. We had a good conversation about the collaboration in Sydney. We will help cross promote the upcoming events. 

I'm pretty sure we're on the same page. We discussed the request is to have a separate CNCG Sydney chapter. The request is not about adding me to the existing KCD. Can you please setup the new chapter for Sydney for me, @AudMonte01\? We have an upcoming meetup soon. I can publish the event if you can help the chapter ready.

**Comment by yongkanghe** [comment]
@AudMonte01 can you please setup a new chapter for CNCG Sydney and make me as the lead organizer? As mentioned earlier, @bradmccoydev and I agreed to keep KCD Sydney and CNCG Sydney separately. For sure, we will collaborate anyway.

**Comment by yongkanghe** [comment]
@AudMonte01 @k8tgreenley is there anything else you need from my side?

**Comment by AudMonte01** [comment]
Hi @yongkanghe - let's schedule a call to discuss. https://calendly.com/audmonte/30min

**Comment by yongkanghe** [comment]
Sure, thanks! Call scheduled.
________________________________

**Comment by AudMonte01** [comment]
Thank you, @yongkanghe - can we do another day, so Katie can join? Ideally Tuesday, Wednesday or Friday which is your Wednesday, Thursday and Saturday morning.

**Comment by yongkanghe** [comment]
No problem. Can you please choose another date/time? I'll travel to Asia on 14th Aug. So, my 15th Singapore time 8am or 9am works better for me. https://calendly.com/k8sug
[https://d3v0px0pttie1i.cloudfront.net/uploads/user/logo/33751186/opengraph_7b71b6b6.png?source=opengraph]<https://calendly.com/k8sug>
Yongkang He<https://calendly.com/k8sug>
Welcome to my scheduling page. Please follow the instructions to add an event to my calendar.
calendly.com




________________________________

**Comment by AudMonte01** [comment]
Thank you - I moved it to the 15th at the same time, @yongkanghe

**Comment by bradmccoydev** [comment]
Hi all, before you meet on the 15th I wanted to express my concerns that I have been thinking about lately.  In summary I believe that this will diverge from what a CNCF community group should be. I have been part of the community for many years now and It is a big part of my life and I would be sad to see it grow into something that I don't recognise anymore.

A CNCF community group to me, should be a simple group run by people in the city/town with the main goals of raising awareness of CNCF and to make folks feel welcome and help to grow the projects by adoption and contributions these are the 3 things that make it go around. 

These days I see growing pains in the groups which has made them come unbalanced and no longer pure CNCF community groups where there is to much empathise on things such as trying to raise too much money from sponsors, too much of organisers trying to grow their own brand awareness, and groups that are run like businesses instead of non profit community group meetups. CNCF community groups are also used as an entry point to grow other groups for example the group is another name but they just use these groups to divert traffic to the other group name to use the CNCF name to get people which damages the brand.

With these concerns I would like to question your intentions and have some rhetorical questions:
- Why do you want to be lead organiser of Sydney if you don't live in Sydney?
- Why do you have meetups in UK, Singapore and Australia and not focus on one?
- Will the group be just another K8SUG franchise trying to get a monopoly on meetups and piggy backing off CNCF
- What are you going to charge sponsors

With these concerns I don't believe you should be the lead organiser and it should be distributed to folks in Sydney for more focus that will more align with CNCF goals of what a meetup should be.

Thank you for listening to my comment, you are doing a great job in the community, keep up the good work!

**Comment by matthewflannery** [comment]
Well written by @bradmccoydev - @AudMonte01 I have not met @yongkanghe so I can't comment on his character however I strongly agree with what Brad has written in regards to geography. 

It would be incredibly difficult for @yongkanghe to meaningfully contribute to organising Sydney events without him living near it.

Further more from a pure observatory perspective, as someone who has sunk my own time and now money into growing the CNCF and Kubernetes community in AU and has done so without any bias or personal gain, I have to say I am a little concerned noting how K8SUG looks on face value. 

If @yongkanghe became an official organiser for the Sydney event, I believe this would be for his own personal gain, perhaps even monetary. 

Why do I believe this? We recently offered free tickets to @yongkanghe for attendees to the K8SUG meetup so that they could come to KCD Sydney, only for @yongkanghe to put his own name forward as one of the "winners" for tickets that were supposed to be raffled off.

It's a little on the nose if you ask me 😀

**Comment by yongkanghe** [comment]
@bradmccoydev

Thank you for sharing your thoughts and concerns. It's clear that you're passionate about the CNCF community and its continued success, and I appreciate your dedication.

I’d like to clarify a few points to ensure we’re all on the same page:

1. **No Active CNCG User Group in Sydney**: Currently, there isn't an active CNCG user group in Sydney. **K8SUG** is stepping in to help fill that gap. Our goal is to revitalize the CNCG Sydney community, and we're committed to doing so in a way that aligns with CNCF’s values.

2. **Local Sydney Organizers**: While we do have meetups in various locations, including the UK and Singapore, we are also focused on building a strong local presence. We have passionate volunteers who are based in Sydney and are eager to lead and grow the local CNCG community. Our intention is not to create a monopoly but to foster community growth where it’s needed most. FYI, @anupamphoghat, @harliu-01 are our organizers based in Sydney. 

3. **Financial Support**: I want to emphasize that we are not making money from this initiative. In fact, I’ve personally been using my own resources and my own pocket money to travel to support the community. Our aim is purely to help the community thrive, not to profit from it.

4. **Need for Sponsors**: Sponsorship is crucial for us to cover basic expenses like food and drinks at events. Additionally, we need our sponsors to support us to expand and contribute globally. We carefully select sponsors who align with our community’s goals and values.

I hope this helps address some of your concerns. We all share a common goal of growing and supporting the CNCF community, and I believe we can work together to make it stronger.

Thank you for your continued commitment and contributions to the community.

**Comment by yongkanghe** [comment]
@matthewflannery 

Thank you for raising your concerns. It’s important that we address these issues transparently to ensure that everyone has the correct information.

I’d like to clarify the situation regarding the free passes to KCD Sydney:

**1. Free Pass Allocation**: We announced three free passes to KCD Sydney during our recent meetup and conducted a quiz to select the winners. Unfortunately, none of the winners expressed interest in claiming the tickets. Rather than letting these tickets go to waste, we decided to allocate them to @yongkanghe and @anupamphoghat, who are both active organizers and contributors to the community.

**2. No Misleading Information**: It’s crucial that we share accurate information to avoid any misunderstandings. The tickets were initially offered to the community, but when there were no takers, they were reassigned to ensure they were utilized effectively.

**3. Personal and Financial Commitment**: I’d like to emphasize that my involvement in the community is driven by a genuine desire to contribute, not for personal or monetary gain. Like many others, I’ve invested my own time and resources to support and grow the CNCF and Kubernetes communities in Australia.

If there are any concerns about our approach or if there’s a preference to withdraw the committed passes to our community, we’re open to discussing it further. Our goal has always been to act in the best interest of the community, and we are committed to transparency and fairness in all our actions.

I appreciate your feedback and look forward to continuing our shared mission to support the CNCF community.

**Comment by matthewflannery** [comment]
Okay @yongkanghe thanks man 

But you literally don't live in Sydney or come to Sydney events so I'm still a bit confused ?

**Comment by AudMonte01** [comment]
As @yongkanghe does not reside in Sydney Australia, per the standards of CNCGs, he cannot become an organizer. This ticket/issue is now closed.

**Comment by yongkanghe** [comment]
I'm eager to know when CNCG Sydney will be revived. It's been years without any active events from the inactive organizing team. We're doing our best to support the community, and we have active volunteers based in Sydney who are willing to help. However, our efforts are limited if we're not given the opportunity to contribute—not to mention, the application we submitted three months ago.
________________________________
